name: CI

on:
  push:
    branches: [ "main" ]
    tags:
      - "*"
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build
    - name: Build
      run: cargo build --all-features
    - name: Coding style
      run: cargo fmt --all -- --check
  
  windows-build:
    name: Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      name: Install Rust
      with:
        toolchain: stable
        override: true
        
    - uses: actions-rs/cargo@v1
      name: Build (default) 
      with:
        command: build
        args: --release

    - uses: actions-rs/cargo@v1
      name: Build (all features)
      with: 
        command: build 
        args: --all-features --release
  
  macos-build:
    name: MacOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      name: Install Rust
      with:
        toolchain: stable
        override: true
    
    - uses: actions-rs/cargo@v1
      name: Build (default) 
      with:
        command: build
        args: --release

    - uses: actions-rs/cargo@v1
      name: Build (all features)
      with: 
        command: build 
        args: --all-features --release
